// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  angular.module('widgets').directive('fillgauge', function() {
    var controller, directive, link, template;
    template = '<div ng-class="\'{{cfg.class2}}\'" style="{{cfg.style2}}">\n  {{cfg.descr}}\n</div>\n<div ng-class="\'{{cfg.class3}}\'" style="{{cfg.style3}}">\n  <burble id=\'fg-{{cfg.id}}\' value=\'{{percentage}}\' ng-model=\'cfg\' ></burble>\n</div>';
    link = function(scope) {
      var ref, ref1, widget;
      widget = scope.ngModel;
      scope.cfg = scope.ngModel.data();
      if ((ref = scope.cfg) != null ? (ref1 = ref.value) != null ? ref1.status : void 0 : void 0) {
        return scope.percentage = scope.cfg.value.status;
      }
    };
    controller = function($scope) {
      var widget;
      widget = $scope.ngModel;
      return widget.on('change', function() {
        link($scope);
        return $scope.$apply();
      });
    };
    return directive = {
      restrict: 'E',
      priority: 10,
      template: template,
      controller: controller,
      link: link
    };
  });

}).call(this);
